import AppKit

/// Polls `NSPasteboard.general` for changes (macOS posts no notification for
/// this) and forwards genuinely new content to a handler.
final class SnipSnapMonitor {

    /// Called on the main thread with each new clipboard payload.
    var onCopy: ((SnipSnapContent) -> Void)?

    private let pasteboard = NSPasteboard.general
    private var lastChangeCount: Int
    private var timer: Timer?
    private let pollInterval: TimeInterval

    /// A `changeCount` value produced by our own paste, to be ignored once.
    private var selfWriteChangeCount: Int?

    /// Pasteboard types that mark content as not-for-history. This is the
    /// convention password managers use (see nspasteboard.org).
    private static let privacyTypes: [NSPasteboard.PasteboardType] = [
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType"),
        .init("com.agilebits.onepassword"),
    ]

    init(pollInterval: TimeInterval = 0.35) {
        self.pollInterval = pollInterval
        self.lastChangeCount = NSPasteboard.general.changeCount
    }

    func start() {
        guard timer == nil else { return }
        let t = Timer(timeInterval: pollInterval, repeats: true) { [weak self] _ in
            self?.poll()
        }
        RunLoop.main.add(t, forMode: .common)
        timer = t
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    /// Tell the monitor that the next change with this count is our own write.
    func ignoreNextChange(count: Int) {
        selfWriteChangeCount = count
    }

    private func poll() {
        let current = pasteboard.changeCount
        guard current != lastChangeCount else { return }
        lastChangeCount = current

        if let mine = selfWriteChangeCount, mine == current {
            selfWriteChangeCount = nil
            return
        }

        let types = pasteboard.types ?? []
        if types.contains(where: { Self.privacyTypes.contains($0) }) { return }

        // Prefer image content; fall back to plain text.
        if let png = pasteboard.data(forType: .png),
           let decoded = ImageUtil.normalizeToPNG(png) {
            onCopy?(.image(png: decoded.png, pixelWidth: decoded.pixelWidth, pixelHeight: decoded.pixelHeight))
            return
        }
        if let tiff = pasteboard.data(forType: .tiff),
           let decoded = ImageUtil.normalizeToPNG(tiff) {
            onCopy?(.image(png: decoded.png, pixelWidth: decoded.pixelWidth, pixelHeight: decoded.pixelHeight))
            return
        }
        if let string = pasteboard.string(forType: .string),
           !string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            onCopy?(.text(string))
        }
    }
}
